import { Router, type IRouter } from "express";
import { sessionMiddleware } from "../lib/session";
import healthRouter from "./health";
import protocolsRouter from "./protocols";
import lotsRouter from "./lots";
import resultsRouter from "./results";
import kineticsRouter from "./kinetics";
import certificatesRouter from "./certificates";
import authRouter from "./auth";
import methodologiesRouter from "./methodologies";
import usersRouter from "./users";
import auditLogsRouter from "./audit-logs";
import settingsRouter from "./settings";
import signaturesRouter from "./signatures";
import attachmentsRouter from "./attachments";
import storageRouter from "./storage";
import catalogRouter from "./catalog";
import backupRouter from "./backup";
import bibliographicReferencesRouter from "./bibliographic-references";
import snapshotsRouter from "./snapshots";
import globalSnapshotsRouter from "./global-snapshots";
import ativoReferencesRouter from "./ativo-references";
import hplcSessionsRouter from "./hplc-sessions";
import hplcSavedAnalysesRouter from "./hplc-saved-analyses";
import hplcWorkspaceRouter from "./hplc-workspace";
import clientAccessRouter from "./client-access";
import coaRouter from "./coa";
import anvisaRouter from "./anvisa";
import companiesRouter from "./companies";
import anvisaNumberBankRouter from "./anvisa-number-bank";

const router: IRouter = Router();

router.use(sessionMiddleware);

router.use(authRouter);
router.use(healthRouter);
router.use(protocolsRouter);
router.use(lotsRouter);
router.use(resultsRouter);
router.use(kineticsRouter);
router.use(certificatesRouter);
router.use(methodologiesRouter);
router.use(usersRouter);
router.use(auditLogsRouter);
router.use(settingsRouter);
router.use(signaturesRouter);
router.use(attachmentsRouter);
router.use(storageRouter);
router.use(catalogRouter);
router.use(backupRouter);
router.use(bibliographicReferencesRouter);
router.use(snapshotsRouter);
router.use(globalSnapshotsRouter);
router.use(ativoReferencesRouter);
router.use(hplcSessionsRouter);
router.use(hplcSavedAnalysesRouter);
router.use(hplcWorkspaceRouter);
router.use(clientAccessRouter);
router.use(coaRouter);
router.use(anvisaRouter);
router.use(companiesRouter);
router.use(anvisaNumberBankRouter);

export default router;
